// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYljJ5-kgqr4sr_RCX-7fVMrmDTG1KbGI',
    appId: '1:23499804389:web:a8a1e5e765ed27137bce0c',
    messagingSenderId: '23499804389',
    projectId: 'juicedates-1c227',
    authDomain: 'juicedates-1c227.firebaseapp.com',
    storageBucket: 'juicedates-1c227.appspot.com',
    measurementId: 'G-PLFGWV62WY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHXKxYhbRno644BofQ0qaJO4V108qVBTs',
    appId: '1:23499804389:android:44978156d0c1fe267bce0c',
    messagingSenderId: '23499804389',
    projectId: 'juicedates-1c227',
    storageBucket: 'juicedates-1c227.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9KvOTuAvqP6AQz-R_bGCCShLPGjPVwqA',
    appId: '1:23499804389:ios:b88befc0caad8bdc7bce0c',
    messagingSenderId: '23499804389',
    projectId: 'juicedates-1c227',
    storageBucket: 'juicedates-1c227.appspot.com',
    iosClientId: '23499804389-dr5osfot4knjot5k5eg2236434emea2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.juicedates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9KvOTuAvqP6AQz-R_bGCCShLPGjPVwqA',
    appId: '1:23499804389:ios:d35c57cfe26735117bce0c',
    messagingSenderId: '23499804389',
    projectId: 'juicedates-1c227',
    storageBucket: 'juicedates-1c227.appspot.com',
    iosClientId: '23499804389-celmm387cjulo2jhh27om1tcs8i88a0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.juicedates.RunnerTests',
  );
}
